spring.application.name=logistics_demo

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2893606150@qq.com
spring.mail.password=cghcnhwlzanxdghe
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.mongodb.uri=mongodb://localhost:27017/logistics_demo

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=3000
spring.redis.database=0

